revise metadata api
easemob/easemob-im-server-sdk pull request #27
Opened 2021-06-22 08:24 UTC by kenuiuc

2021-06-22 08:54 UTC, harry-hao requested changes

2021-06-22 08:54 UTC, harry-hao commented on im-sdk-core/src/main/java/com/easemob/im/server/api/metadata/user/capacity/MetadataCapacity.java
> +                .map(MetadataCapacityResponse::getCapacity);
Capacity 是什么单位？这个叫Capacity 确实是容量吧？会不会有surprise？

2021-06-22 08:54 UTC, harry-hao commented on im-sdk-core/src/main/java/com/easemob/im/server/api/metadata/user/delete/MetadataDeleteResponse.java
> +    private boolean success;
Not so sure about that, please keep it a wrapper type.

2021-06-22 08:54 UTC, harry-hao commented on im-sdk-core/src/main/java/com/easemob/im/server/api/metadata/user/capacity/MetadataCapacityResponse.java
> +    private long capacity;
Not so sure about that, please keep it a wrapper type.

2021-06-22 08:54 UTC, harry-hao commented on im-sdk-core/src/main/java/com/easemob/im/server/api/metadata/user/delete/MetadataDeleteResponse.java
> +            throw new EMInvalidArgumentException("metadata deletion success flag is null");
Remove this check and try to provide some fallback.

2021-06-22 08:54 UTC, harry-hao commented on im-sdk-core/src/main/java/com/easemob/im/server/api/metadata/user/capacity/MetadataCapacityResponse.java
> +        if (capacity == null) {
Remove this check and try to provide some fallback.

2021-06-22 08:54 UTC, harry-hao commented on im-sdk-core/src/main/java/com/easemob/im/server/api/metadata/user/set/MetadataSet.java
> +                            metadata.forEach(clientForm::attr);
Cool!

2021-06-22 08:54 UTC, harry-hao commented on pom.xml
> +        <commons-lang3.version>3.12.0</commons-lang3.version>
To keep our dependencies at minimum, please remove commons-lang and guava.

2021-06-23 10:08 UTC, kenuiuc commented on im-sdk-core/src/main/java/com/easemob/im/server/api/metadata/user/capacity/MetadataCapacity.java
> +                .map(MetadataCapacityResponse::getCapacity);
单位是Bytes, 这个单位在MetadataApi类的javadoc里有写
但是所谓的 "capacity" 其实是表示该 app 的 metadata 已经用了多少空间，而不是可用的空间大小
所以我感觉其实应该叫 "usage"
在 REST API 里一直用的是 “capacity”, 这个我当时写API的时候疏忽了 :(

2021-06-23 10:24 UTC, harry-hao commented on im-sdk-core/src/main/java/com/easemob/im/server/api/metadata/user/capacity/MetadataCapacity.java
> +                .map(MetadataCapacityResponse::getCapacity);
Ok, 那就capacity吧，最好返回个对象，比如：
```
{
  bytesUsed: ...
}
```

2021-06-23 10:34 UTC, harry-hao approved these changes

2021-06-23 10:35 UTC, merged